services:
  - type: web
    name: gemini-audio-proxy
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
